'''
Created on Mar 8, 2018

@author: abelit
'''


import sys, getopt

opts, args = getopt.getopt(sys.argv[1:], "hvc:o:",["help", "version", "file=", "conf="])


def reportopt(var,value):
    return {
            '-c': lambda value: print(value),
            '--conf': lambda value: print(value),
            '-o': lambda value: print(value),
            '--file': lambda value: print(value), 
            
            '-h': lambda value: usage(), 
            '--help': lambda value: print('help'), 
            '-v': lambda value: print('V3.14'), 
            '--version': lambda value: print('V3.14'), 
    }[var](value) 


def usage():
    print('DBReport: usage of this procedure.')
    print('-h | --help, get help information of dbreport.')
    print('-v | --version, get version of dbreport.')
    print('-c | --conf, assign the configuration to dbreport, eg. dbreport -c "/home/oracle/dbreport.json" or dbreport --conf="/home/oracle/dbreport.json"')
    print('-o | --outfile, assign the path of pdf report which is generated by dbrepor.')

for op, value in opts:
    reportopt(op,value)